version: "3"
services:
    web-app-service:
        container_name: spring-boot-web-app
        build: 
            context: ./web-app
        env_file:
            ./web-app.env
    web-server-service:
        image: nginx:alpine
        container_name: web-server
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:80
        depends_on:
            - web-app-service
