version: "3"
services:
    tidal-java-service:
        container_name: tidal-spring-boot-app
        build: 
            context: ./tidal-spring-app
            args: 
                - APPLICATION_JAR=**ADD JAR FILE URL HERE**
        env_file:
            ./tidal-spring-app/tidal-spring-app.env
    nginx:
        image: nginx:alpine
        container_name: tidal-web-server
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:80
        depends_on:
            - tidal-java-service
